version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: music
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw
    volumes:
      - music-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
      - shared_network
  

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  music-pgdata:

networks:
  shared_network:
    external: true